name: inject.example.train
description: A more complex example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^1.8.1
  build_test: ^0.10.1+1
  build_web_compilers: ^2.9.0
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.14.2
